#!/usr/bin/env ruby

require "bundler/setup"
require "jambots"

BASIC_ARGS = ["chat", "-b", "dev"]

class DevBot < Jambots::Cli
  # load the chat description and options
  chat_options
  # add a new option to the chat command
  option :refs, type: :array, desc: "Add reference messages from files"
  def chat(query)
    chat_controller = Jambots::Controllers::ChatController.new(options)
    add_reference_messages(chat_controller.conversation)
    chat_controller.chat(query)
  end

  private

  def add_reference_messages(conversation)
    return unless options[:refs]

    options[:refs].each do |file_path|
      file_content = File.read(file_path)
      conversation.add_message("system", "#{file_path}\n---\n #{file_content}")
    end
  end
end

DevBot.start(BASIC_ARGS + ARGV)
